CREATE DATABASE QL_THUCHI;
USE QL_THUCHI;

CREATE TABLE QuyenTruyCap (
    MAQUYEN CHAR(20) PRIMARY KEY, 
    TENQUYEN NVARCHAR(100) NOT NULL UNIQUE,
);

CREATE TABLE TaiKhoan (
    MATAIKHOAN CHAR(20) PRIMARY KEY, 
    MAQUYEN CHAR(20),
	TENDANGNHAP VARCHAR(40),
	MATKHAU VARCHAR(40),
	EMAIL VARCHAR(40),
	ISEMAILCONFIRMED INT,
	EMAILCONFIRMATIONTOKEN NVARCHAR(100),
	OTP INT,
	 CONSTRAINT FK_TK_QTC FOREIGN KEY (MAQUYEN) REFERENCES QuyenTruyCap(MAQUYEN)
);
CREATE TABLE KhachHang (
    MAKH CHAR(20) PRIMARY KEY, 
	MATAIKHOAN CHAR(20),
    HOTEN NVARCHAR(50),
	NGAYSINH DATE,
	SODT CHAR(11),
	XU INT,
	AVATAR VARCHAR(150),
	CONSTRAINT FK_KH_TK FOREIGN KEY (MATAIKHOAN) REFERENCES TaiKhoan(MATAIKHOAN)
);

INSERT INTO QuyenTruyCap (MAQUYEN, TENQUYEN)
VALUES 
    ('Q001', N'Ph? Huynh'),
    ('Q002', N'Con Cái');

INSERT INTO TaiKhoan (MATAIKHOAN, MAQUYEN, TENDANGNHAP, MATKHAU, EMAIL, ISEMAILCONFIRMED, EMAILCONFIRMATIONTOKEN, OTP)
VALUES 
    ('TK0001', 'Q001', 'admin', '123456', 'khangt2110@gmail.com', 1, NULL, NULL),
    ('TK0002', 'Q002', 'Khang12', '123456', 'khangtuong2110@gmail.com', 1, NULL, NULL);
INSERT INTO KhachHang (MAKH, MATAIKHOAN, HOTEN, NGAYSINH, SODT, XU, AVATAR)
VALUES 
('KH0001', 'TK0001', N'Tý?ng T?n Khang', '2004-08-09', '0374075809', 100, 'images/avatar4.png'),
('KH0002', 'TK0002', N'Nguy?n Výõng Ðào', '1999-10-11', '09808208', 100, Null)

select* from QuyenTruyCap
select* from TaiKhoan
select* from KhachHang

UPDATE QuyenTruyCap
SET TENQUYEN = N'Ph? Huynh'
WHERE MAQUYEN = 'Q001';

DELETE FROM TaiKhoan WHERE MATAIKHOAN = 'tk0003              ';

SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'TaiKhoan';
